name: Test School Vanilla JS

on:
  workflow_call:
    inputs:
        team-name:
            required: true
            type: string
    secrets:
        test-repo:
            required: true
        auth-token:
            required: true
        backend-url: 
            required: true
        auth-key:
            required: true

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          path: tests

      - name: move test files
        run: mv tests/*.test.js src/

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci

      - name: run test on bug 01
        shell: bash {0}
        run: |
          set +e
          npx jest -t "Local Storage Functions" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-201"
            }'
          fi
          exit ${result}
        continue-on-error: true

      - name: run test on bug 02
        shell: bash {0}
        run: |
          set +e
          npx jest -t "Add transactions" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-202"
            }'
          fi
          exit ${result}
        continue-on-error: true

      - name: run test on bug 03
        shell: bash {0}
        run: |
          set +e
          npx jest -t "Update Values Functions" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-203"
            }'
          fi
          exit ${result}
        continue-on-error: true

      - name: run test on bug 04
        shell: bash {0}
        run: |
          set +e
          npx jest -t "Transaction List DOM" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-204"
            }'
          fi
          exit ${result}
        continue-on-error: true

      - name: run test on bug 05
        shell: bash {0}
        run: |
          set +e
          npx jest -t "chart" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-205"
            }'
          fi
          exit ${result}
        continue-on-error: true

      - name: run test on bug 06
        shell: bash {0}
        run: |
          set +e
          npx jest -t "Generating Report" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-206"
            }'
          fi
          exit ${result}
        continue-on-error: true

      - name: run test on bug 07
        shell: bash {0}
        run: |
          set +e
          npx jest -t "Category Management" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-207"
            }'
          fi
          exit ${result}
        continue-on-error: true

      - name: run test on bug 08
        shell: bash {0}
        run: |
          set +e
          npx jest -t "CSS Validations" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-208"
            }'
          fi
          exit ${result}
        continue-on-error: true

      - name: run test on bug 09
        shell: bash {0}
        run: |
          set +e
          npx jest -t "More Test cases" > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
            echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-209"
            }'
          fi
          exit ${result}
        continue-on-error: true
